# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in windowrules-apps.conf

# Fcitx5 input method
# XMODIFIERS stays for XWayland/X11 legacy apps.
env = XMODIFIERS,@im=fcitx
env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,ibus
