set number rnu
set numberwidth=1
set background=light
set mouse=a

highlight LineNr ctermfg=DarkGrey

"set cursorline
"highlight CursorLineNr ctermfg=Yellow
call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'

call plug#end()
set termguicolors
set background=dark
colorscheme gruvbox

"if &t_Co > 1
"    syntax enable
"endif


let $LOCALFILE=expand("~/.vimrc_local")
if filereadable($LOCALFILE)
    source $LOCALFILE
endif
