#!/bin/bash
#TODO
function x_oslmd5 {
  openssl rsa -modulus -noout | md5sum;
}


pullgitrep() {
  excluded=("vendor" "node_modules" "dist" "build" "tmp" ".local/share")

  initial_dir=$(pwd)

  find_command="find ~ -type d -name '.git'"

  for term in "${excluded[@]}"; do
    find_command="$find_command ! -path \"*/$term/*\""
  done

  if command -v batcat &>/dev/null; then
    preview_cmd="batcat --style=numbers --color=always 2>/dev/null"
  elif command -v bat &>/dev/null; then
    preview_cmd="bat --style=numbers --color=always 2>/dev/null"
  else
    preview_cmd="cat 2>/dev/null"
  fi  

  repo_dir=$(eval $find_command | fzf --preview "$preview_cmd {}/../README.md" \
    --preview-window=up:30%:wrap \
    --query "$1" \
    --border)

  if [ -z "$repo_dir" ]; then
    echo "No repo selected."
    return 1
  fi

  repo_path=$(dirname "$repo_dir")

  if [ ! -d "$repo_path/.git" ]; then
    echo "Not valid."
    return 1
  fi

  echo "Pulling the latest changes in $repo_path..."
  cd "$repo_path" || return 1
  git pull

  cd "$initial_dir" || return 1
}

diff_tar () {
  if [ "$#" -ne 2 ]; then
    echo "Usage: $0 archive1.tar.gz archive2.tar.gz"
    exit 1
  fi

  local ARCHIVE1="$1"
  local ARCHIVE2="$2"
  local bn1="${ARCHIVE1##*/}"
  bn1="${bn1%.*}"
  local bn2="${ARCHIVE2##*/}"
  bn2="${bn2%.*}"
  local common=$(printf "%s\n%s\n" "$bn1" "$bn2" | awk 'NR==1 {line=$0} NR==2 {for(i=1;i<=length && substr($0, i, 1)==substr(line, i, 1); i++); print substr($0, 1, i-1)}')

  strip_top_folder_if_needed() {
    local dir="$1"
    local entries=("$dir"/*)

    if [ ${#entries[@]} -eq 1 ] && [ -d "${entries[0]}" ]; then
      local subdir="${entries[0]}"
      mv "$subdir"/* "$dir" 2>/dev/null
      rmdir "$subdir"
    fi
  }

  DIR1=$(mktemp -d "/tmp/${bn1}_XXXX")
  DIR2=$(mktemp -d "/tmp/${bn2}_XXXX")


  tar -xzf "$ARCHIVE1" -C "$DIR1"
  tar -xzf "$ARCHIVE2" -C "$DIR2"

  strip_top_folder_if_needed "$DIR1"
  strip_top_folder_if_needed "$DIR2"

  DIFF_FILE=".${bn1}-${bn2}_${EPOCHSECONDS}.diff"

  diff -Naur --no-dereference --exclude=".git" "$DIR1" "$DIR2" > "$DIFF_FILE"
  MODIFIED_FILES=$(grep -E '(^\+\+|^\-\-)' "$DIFF_FILE" | cut -d' ' -f2 | sed 's|.*/||' | awk 'NF' | awk '{print $1}'| sort | uniq -c)
  echo -e "=> Diff $DIFF_FILE,\n${MODIFIED_FILES}"
  dc <<<"1 102*P105P108P101P115P4 8*P100 2+P111P117P110P100P59 1-P32P $(echo -e "${MODIFIED_FILES}" | wc -l) p"
}

dush() { local t="${1:-.}"; [ -f "$t" ] && du -sh "$t" 2>/dev/null || du -sh "$t"/.[^.]* "$t"/* 2>/dev/null | sort -hr; }
