#!/bin/bash
#TODO
function x_oslmd5 {
  openssl rsa -modulus -noout | md5sum;
}


x_pullRepo() {
  excluded=("vendor" "node_modules" "dist" "build" "tmp" ".local/share")

  initial_dir=$(pwd)

  find_command="find ~ -type d -name '.git'"

  for term in "${excluded[@]}"; do
    find_command="$find_command ! -path \"*/$term/*\""
  done

  if command -v batcat &>/dev/null; then
    preview_cmd="batcat --style=numbers --color=always 2>/dev/null"
  elif command -v bat &>/dev/null; then
    preview_cmd="bat --style=numbers --color=always 2>/dev/null"
  else
    preview_cmd="cat 2>/dev/null"
  fi  

  repo_dir=$(eval $find_command | fzf --preview "$preview_cmd {}/../README.md" \
    --preview-window=up:30%:wrap \
    --query "$1" \
    --border)

  if [ -z "$repo_dir" ]; then
    echo "No repo selected."
    return 1
  fi

  repo_path=$(dirname "$repo_dir")

  if [ ! -d "$repo_path/.git" ]; then
    echo "Not valid."
    return 1
  fi

  echo "Pulling the latest changes in $repo_path..."
  cd "$repo_path" || return 1
  git pull

  cd "$initial_dir" || return 1
}

